---

- name: install apache in node1
  hosts: n1
  become: yes

  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest
      update_cache: true

  - name: start apache
    service:
      name: apache2
      state: started

  - name: enable apache2
    service:
      name: apache2
      enabled: true
...