---

- name: install httpd in node3 server
  hosts: g1
  become: yes

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "amazon"


  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "amazon"

  - name: enable httpd
    service:
      name: httpd
      enabled: true
    when: ansible_distribution == "amazon"



- name: install apache in node1
  hosts: g1
  become: yes

  tasks:
  - name: install apache
    apt:
      name: apache2
      state: latest
      update_cache: true
    when: ansible_distribution == "ubuntu"

  - name: start apache
    service:
      name: apache2
      state: started
    when: ansible_distribution == "ubuntu"

  - name: enable apache2
    service:
      name: apache2
      enabled: true
    when: ansible_distribution == "ubuntu"
...